name: Patch Release (scheduled)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # full git history

      - name: Bump version and tag
        uses: anothrNick/github-tag-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Update CHANGELOG
        id: changelog
        run: echo "::set-output name=diff::$(./update-version.sh [FIXME] $GIT_BRANCH)"
        with:
          GIT_BRANCH: 13.x

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            $CHANGELOG
          draft: false
          prerelease: false
          env: ${{ steps.changelog.outputs.diff }}
